language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - jruby
  - rbx-2
gemfile:
  - test/gemfiles/sass_3_2.gemfile
  - test/gemfiles/sass_3_3.gemfile
  - test/gemfiles/sass_head.gemfile
before_install:
  - "npm install"
matrix:
  allow_failures:
    # rbx has issues https://github.com/rubinius/rubinius/issues/3060
    - rvm: rbx-2
    - gemfile: test/gemfiles/sass_head.gemfile
notifications:
  slack: heybb:3n88HHilXn76ji9vV4gL819Y
