language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - jruby
  - rbx
gemfile:
  - test/gemfiles/sass_3_2.gemfile
  - test/gemfiles/sass_3_3.gemfile
  - test/gemfiles/sass_head.gemfile
before_install:
  - "npm install node-sass mincer ejs"
matrix:
  allow_failures:
    - gemfile: test/gemfiles/sass_head.gemfile
notifications:
  slack: heybb:3n88HHilXn76ji9vV4gL819Y
